---
- name: Ensure curl-minimal is not installed (RHEL family)
  ansible.builtin.dnf:
    name: curl-minimal
    state: absent
  when: ansible_facts.os_family == "RedHat"

- name: Ensure baseline packages are installed (RHEL family)
  ansible.builtin.dnf:
    name: "{{ linux_baseline_packages }}"
    state: present
    update_cache: true
  when: ansible_facts.os_family == "RedHat"

- name: Ensure chrony is enabled and running (RHEL family)
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  when: ansible_facts.os_family == "RedHat"
