- name: Test connectivity
  hosts: all
  gather_facts: false

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
      register: ping_out

    - name: Show ping result
      ansible.builtin.debug:
        var: ping_out.ping
